language: php
php:
  - '8.0'

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=etc/phpcs/ruleset.xml
  - vendor/bin/psalm --config=etc/psalm/psalm.xml
  - vendor/bin/phpstan analyze -c etc/phpstan/phpstan.neon
  - vendor/bin/phpunit -c etc/phpunit/phpunit.xml
